version: '3.6'

services:
  transcriber:
    build:
      context: ./transcriber
      dockerfile: Dockerfile
    ports:
      - 8090:8000
  assister:
    build:
      context: ./assister
      dockerfile: Dockerfile
    ports:
      - 8091:8080
  translator:
    build:
      context: ./translator
      dockerfile: Dockerfile
    ports:
      - 8092:8000